# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master
  - releases/rc

resources:
  containers:
    - container: u18
      image: edimarlnx/maven3-jdk-11-gpg2

jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        ubuntu18:
          containerResource: u18
    container: $[ variables['containerResource'] ]
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx1024m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'clean package'
#      - task: PublishBuildArtifacts@1
#        inputs:
#          pathtoPublish: '$(System.DefaultWorkingDirectory)'
#          artifactName: target

  - job: Deploy
    variables:
      - group: Deploy-keys
      - name: GPG_DIR
        value: $(Agent.TempDirectory)
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        ubuntu18:
          containerResource: u18
    container: $[ variables['containerResource'] ]
    steps:
      - task: DownloadSecureFile@1
        inputs:
          secureFile: secring.gpg
#      - task: DecryptFile@1
#        inputs:
#          cipher: 'aes-256-cbc'
#          inFile: $(GPG_DIR)/secring.gpg.enc
#          passphrase: $(ENCRYPTION_PASSWORD)
#          outFile: $(GPG_DIR)/secring.gpg
      - task: DownloadSecureFile@1
        inputs:
          secureFile: pubring.gpg
#      - task: DecryptFile@1
#        inputs:
#          cipher: 'aes-256-cbc'
#          inFile: $(GPG_DIR)/pubring.gpg.enc
#          passphrase: $(ENCRYPTION_PASSWORD)
#          outFile: $(GPG_DIR)/pubring.gpg
      - bash: gpg --batch --import $(GPG_DIR)/secring.gpg && gpg --list-keys
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx1024m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'deploy -B -Dmaven.repo.local=/mvn2m/.m2/repository -Dmaven.test.skip=true -Dfindbugs.skip=true -DperformRelease=true --settings deployment/settings.xml
            -Dgpg.dir=$GPG_DIR -Dsonatype-username=$(SONATYPE_USERNAME) -Dsonatype-password=$(SONATYPE_PASSWORD)'
#      - task: DownloadBuildArtifacts@0
#        displayName: 'Download Build Artifacts'
#        inputs:
#          pathtoPublish: '$(System.DefaultWorkingDirectory)'
#          artifactName: target
    dependsOn: Build
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/releases/rc')

